var bankName;
console.log("Before Initialize value:", bankName);

var bankName;
console.log("Before Initialize typeOf:", typeof bankName);

var bankName = "SBI Bank";
console.log("After Initialize value:", bankName);

var bankName = "SBI Bank";
console.log("After Initialize typeOf:", typeof bankName);
console.log("---------------------------");

var marks = "90%";
console.log("marks:",marks);
console.log("data type of marks:", typeof marks);
console.log("---------------------------");

var isWorking;
console.log("Before Initialize value:", isWorking);
console.log("Before Initialize typeOf:", isWorking);

var isWorking = true;
console.log("After Initialize value:", isWorking);
console.log("After Initialize typeOf:", typeof isWorking);
console.log("---------------------------");

var totalCount = "Hundred and seven";
console.log("totalCount:", totalCount);
console.log("type of data:",typeof totalCount);
var totalCount = 107;
console.log("Update total count:",totalCount);
console.log("Update type of data:",typeof totalCount);
